import type { CompanyState, DeployAgent, StartupInput } from './types'

export const DEFAULT_STARTUP: StartupInput = {
  name: 'VetPulse AI',
  industry: 'AI SaaS · Veterinary Healthcare',
  budget: '$250,000',
  timeline: '12 months to Series A',
  targetCustomers: 'Independent pet clinics (1-5 veterinarians)',
  fundingStage: 'Pre-Seed',
  goals: 'Launch MVP, sign 10 pilot clinics, raise $1.5M seed round',
  documentName: 'VetPulse_Pitch_Deck.pdf',
}

export const DEPLOY_AGENTS: DeployAgent[] = [
  { id: 'ceo', name: 'CEO Agent', icon: '👔', status: 'pending' },
  { id: 'founder', name: 'Founder Persona Agent', icon: '🎯', status: 'pending' },
  { id: 'market', name: 'Market Intelligence Agent', icon: '📊', status: 'pending' },
  { id: 'investor', name: 'Investor Intelligence Agent', icon: '💰', status: 'pending' },
  { id: 'finance', name: 'Finance Agent', icon: '📈', status: 'pending' },
  { id: 'growth', name: 'Growth Agent', icon: '🚀', status: 'pending' },
  { id: 'treasury', name: 'Treasury Agent', icon: '🏦', status: 'pending' },
  { id: 'governance', name: 'Governance Agent', icon: '⚖️', status: 'pending' },
  { id: 'board', name: 'Board of Directors', icon: '🏛️', status: 'pending' },
]

export function generateCompanyState(startup: StartupInput = DEFAULT_STARTUP): CompanyState {
  return {
    startup,
    overallReadiness: 72,
    readiness: [
      { label: 'Market Readiness', score: 78, trend: 5 },
      { label: 'Product Readiness', score: 65, trend: 8 },
      { label: 'Funding Readiness', score: 71, trend: 3 },
      { label: 'Hiring Readiness', score: 58, trend: -2 },
      { label: 'Legal Readiness', score: 82, trend: 4 },
      { label: 'Growth Readiness', score: 69, trend: 6 },
      { label: 'Treasury Readiness', score: 74, trend: 2 },
    ],
    ceo: {
      mission: 'Empower independent veterinary clinics with AI-driven patient triage, scheduling optimization, and revenue intelligence.',
      vision: 'Become the operating system for 50,000+ pet clinics globally by 2030.',
      roadmap: [
        { phase: 'Q1 2026 — MVP Launch', items: ['AI triage chatbot', 'Clinic dashboard', 'EHR integration (Vetspire)'] },
        { phase: 'Q2 2026 — Pilot Program', items: ['10 design partner clinics', 'Case study generation', 'Pricing validation'] },
        { phase: 'Q3 2026 — Seed Round', items: ['$1.5M raise', 'Hire 3 engineers', 'Expand to 50 clinics'] },
        { phase: 'Q4 2026 — Scale', items: ['Self-serve onboarding', 'Multi-clinic groups', 'API marketplace'] },
      ],
      priorities: [
        'Close 3 design partner LOIs by end of month',
        'Complete Vetspire API integration',
        'Finalize seed deck with investor intelligence',
        'Launch paid pilot pricing at $299/clinic/month',
      ],
      risks: [
        'EHR integration complexity may delay pilot by 4-6 weeks',
        'Competitor PawPrint AI raised $8M — accelerated GTM needed',
        'Regulatory uncertainty around AI diagnosis disclaimers',
        'Burn rate exceeds plan if hiring starts before seed close',
      ],
      nextActions: [
        'Schedule demo with Blue Ridge Veterinary Group (lead score: 94)',
        'Submit HIPAA compliance questionnaire to legal advisor',
        'Approve $500 marketing campaign for vet conference booth',
        'Send warm intro request to Bessemer via portfolio founder',
      ],
      recommendations: [
        'Focus on clinics with 2-3 vets — highest ROI segment per market analysis',
        'Position as "revenue recovery" not "AI triage" — 3x higher conversion',
        'Delay Series A prep until 25 paying clinics — current trajectory supports Q4 2026',
        'Allocate 40% of treasury to engineering, 25% to GTM for next quarter',
      ],
    },
    departments: [
      {
        id: 'ceo', name: 'CEO Agent', icon: '👔', status: 'active', budget: 0, spent: 0, progress: 100,
        riskScore: 12, reputationScore: 94,
        outputSummary: 'Strategic plan synthesized from pitch deck and market data.',
        output: {
          title: 'CEO Agent — Strategic Synthesis',
          confidenceScore: 91,
          reasoning: 'Cross-referenced pitch deck claims with TAM analysis, competitive landscape, and founder background. High confidence in market opportunity; moderate confidence in timeline assumptions.',
          generatedAt: '2026-06-20T10:32:00Z',
          sections: [
            { heading: 'Strategic Position', items: ['Category: Vertical AI SaaS for veterinary clinics', 'Moat: Proprietary clinic workflow data + EHR integrations', 'Beachhead: US independent clinics (32,000 TAM)'] },
            { heading: 'Key Decisions', items: ['Pursue B2B SaaS model over marketplace', 'Price at $299/mo per clinic (validated against willingness-to-pay surveys)', 'Partner-first GTM over paid ads for first 50 customers'] },
            { heading: '90-Day OKRs', items: ['O1: Launch MVP with 3 core features (Score: on track)', 'O2: 10 pilot clinics signed (Score: 3/10)', 'O3: Seed deck ready for 20 investor meetings (Score: 70%)'] },
          ],
        },
      },
      {
        id: 'product', name: 'Product Agent', icon: '📦', status: 'active', budget: 45000, spent: 12000, progress: 68,
        riskScore: 28, reputationScore: 87,
        outputSummary: 'MVP feature prioritization and user journey mapped.',
        output: {
          title: 'Product Agent — MVP Specification',
          confidenceScore: 88,
          reasoning: 'Analyzed PRD document, competitor feature matrices, and 12 clinic interview transcripts (simulated from industry reports).',
          generatedAt: '2026-06-20T10:35:00Z',
          sections: [
            { heading: 'Core Features (P0)', items: ['AI Patient Triage Chatbot — symptom intake, urgency scoring', 'Smart Scheduling — fill cancellation gaps, reduce no-shows 23%', 'Revenue Dashboard — missed billing detection, upsell alerts'] },
            { heading: 'User Journey', items: ['Clinic admin onboarding: 15 min self-serve setup', 'Vet daily workflow: triage review → schedule → revenue check', 'Pet owner touchpoint: SMS triage link pre-appointment'] },
            { heading: 'Technical Stack', items: ['Next.js frontend, FastAPI backend, PostgreSQL', 'OpenAI GPT-4o for triage, custom fine-tune planned Q3', 'Vetspire + ezyVet EHR integrations'] },
          ],
        },
      },
      {
        id: 'cto', name: 'CTO Agent', icon: '💻', status: 'active', budget: 80000, spent: 22000, progress: 55,
        riskScore: 35, reputationScore: 82,
        outputSummary: 'Architecture blueprint and integration roadmap.',
        output: {
          title: 'CTO Agent — Technical Architecture',
          confidenceScore: 85,
          reasoning: 'Evaluated scalability requirements for 500 concurrent clinics, HIPAA compliance needs, and integration complexity with legacy EHR systems.',
          generatedAt: '2026-06-20T10:38:00Z',
          sections: [
            { heading: 'Architecture', items: ['Microservices: API gateway, triage engine, scheduling optimizer, analytics', 'AWS deployment: ECS Fargate, RDS PostgreSQL, ElastiCache Redis', 'HIPAA: BAA with AWS, encryption at rest + in transit'] },
            { heading: 'Integration Roadmap', items: ['Week 1-4: Vetspire read/write API', 'Week 5-8: ezyVet webhook integration', 'Week 9-12: Twilio SMS for patient triage links'] },
            { heading: 'Risk Mitigation', items: ['EHR API rate limits → implement queue-based sync', 'AI hallucination → mandatory vet review gate on all triage outputs', 'Data breach → SOC 2 Type I by Q3 2026'] },
          ],
        },
      },
      {
        id: 'development', name: 'Development Agent', icon: '⚡', status: 'processing', budget: 60000, spent: 18000, progress: 42,
        riskScore: 40, reputationScore: 79,
        outputSummary: 'Sprint plan and velocity projections.',
        output: {
          title: 'Development Agent — Sprint Plan',
          confidenceScore: 82,
          reasoning: 'Based on 2-person engineering team capacity and feature complexity estimates from product spec.',
          generatedAt: '2026-06-20T10:40:00Z',
          sections: [
            { heading: 'Current Sprint (Week 3)', items: ['Triage chatbot MVP — 80% complete', 'Clinic auth + onboarding flow — 60% complete', 'Vetspire OAuth integration — 30% complete'] },
            { heading: 'Velocity', items: ['Average: 34 story points/sprint', 'Projected MVP completion: 6 weeks', 'Buffer for EHR integration: +3 weeks'] },
            { heading: 'Blockers', items: ['Vetspire sandbox API access pending (requested 5 days ago)', 'Need HIPAA legal review before production deploy'] },
          ],
        },
      },
      {
        id: 'finance', name: 'Finance Agent', icon: '📈', status: 'active', budget: 15000, spent: 4500, progress: 85,
        riskScore: 22, reputationScore: 91,
        outputSummary: 'Financial model with 18-month projections.',
        output: {
          title: 'Finance Agent — Financial Model',
          confidenceScore: 89,
          reasoning: 'Built bottom-up model from pricing assumptions, clinic acquisition costs, and comparable SaaS metrics (VetTech benchmarks).',
          generatedAt: '2026-06-20T10:42:00Z',
          sections: [
            { heading: 'Revenue Projections', items: ['Month 6: $8,970 MRR (30 clinics × $299)', 'Month 12: $44,850 MRR (150 clinics)', 'Month 18: $119,600 MRR (400 clinics)'] },
            { heading: 'Unit Economics', items: ['CAC: $1,200 (partner-led GTM)', 'LTV: $10,764 (36-month retention × $299)', 'LTV/CAC: 8.97x', 'Gross margin: 82%'] },
            { heading: 'Burn & Runway', items: ['Monthly burn: $18,500', 'Current runway: 13.5 months on $250K', 'Seed raise ($1.5M) extends runway to 36+ months'] },
          ],
        },
      },
      {
        id: 'treasury', name: 'Treasury Agent', icon: '🏦', status: 'active', budget: 250000, spent: 48500, progress: 90,
        riskScore: 18, reputationScore: 93,
        outputSummary: 'Wallet allocations and spend policies configured.',
        output: {
          title: 'Treasury Agent — Allocation Plan',
          confidenceScore: 92,
          reasoning: 'Optimized allocation based on stage-appropriate benchmarks for pre-seed AI SaaS companies.',
          generatedAt: '2026-06-20T10:44:00Z',
          sections: [
            { heading: 'Allocation', items: ['Engineering: 40% ($100,000)', 'Go-to-Market: 25% ($62,500)', 'Operations: 15% ($37,500)', 'Legal/Compliance: 10% ($25,000)', 'Reserve: 10% ($25,000)'] },
            { heading: 'Spend Policies', items: ['Auto-approve: <$200 operational expenses', 'Founder approval: $200-$2,000', 'Board approval: >$2,000 or new vendor contracts'] },
            { heading: 'Treasury Health', items: ['Burn rate within 8% of plan', '18.5 months runway at current spend', 'No critical cash flow gaps projected before seed'] },
          ],
        },
      },
      {
        id: 'hr', name: 'HR Agent', icon: '👥', status: 'idle', budget: 20000, spent: 2000, progress: 30,
        riskScore: 45, reputationScore: 76,
        outputSummary: 'Hiring plan for first 5 employees.',
        output: {
          title: 'HR Agent — Hiring Plan',
          confidenceScore: 78,
          reasoning: 'Modeled hiring sequence based on product roadmap critical path and seed funding timeline.',
          generatedAt: '2026-06-20T10:46:00Z',
          sections: [
            { heading: 'Priority Hires', items: ['Senior Full-Stack Engineer — post-seed, Month 1 ($140K)', 'Veterinary Domain Expert (part-time advisor) — immediate ($3K/mo)', 'Head of Sales — post 10 pilots, Month 3 ($120K + commission)'] },
            { heading: 'Compensation Benchmarks', items: ['Engineering: 75th percentile for seed-stage SF remote', 'Equity pool: 15% reserved, 1.5-3% for first 5 hires', 'Benefits: health stipend $500/mo pre-seed'] },
          ],
        },
      },
      {
        id: 'growth', name: 'Growth Agent', icon: '🚀', status: 'active', budget: 35000, spent: 8500, progress: 52,
        riskScore: 30, reputationScore: 84,
        outputSummary: 'GTM strategy with channel prioritization.',
        output: {
          title: 'Growth Agent — GTM Strategy',
          confidenceScore: 86,
          reasoning: 'Analyzed veterinary SaaS adoption patterns, conference calendars, and partnership opportunities.',
          generatedAt: '2026-06-20T10:48:00Z',
          sections: [
            { heading: 'Channel Strategy', items: ['Primary: Vet conference booths (VMX, WVC) — $15K budget', 'Secondary: Vetspire marketplace listing — free, high intent', 'Tertiary: LinkedIn content + vet community partnerships'] },
            { heading: 'Pilot Program', items: ['Free 60-day pilot → $299/mo conversion target: 70%', 'Design partner benefits: co-marketing, feature input, 50% discount Year 1', '3 LOIs signed, 7 in pipeline'] },
            { heading: 'Metrics', items: ['Target: 10 pilots by Q2 end', 'Pipeline value: $35,880 ARR', 'Conversion rate: 42% (demo → pilot)'] },
          ],
        },
      },
      {
        id: 'marketing', name: 'Marketing Agent', icon: '📣', status: 'active', budget: 25000, spent: 6200, progress: 48,
        riskScore: 25, reputationScore: 81,
        outputSummary: 'Brand positioning and campaign plan.',
        output: {
          title: 'Marketing Agent — Brand & Campaigns',
          confidenceScore: 84,
          reasoning: 'Positioning tested against 5 messaging variants; "Revenue Recovery for Vet Clinics" outperformed by 3x.',
          generatedAt: '2026-06-20T10:50:00Z',
          sections: [
            { heading: 'Positioning', items: ['Tagline: "Recover $50K/year in missed revenue per clinic"', 'Category: Veterinary Revenue Intelligence', 'Differentiator: AI triage + revenue optimization (not just scheduling)'] },
            { heading: 'Campaigns', items: ['VMX 2026 booth — $8,000 (pending approval)', 'Case study: Blue Ridge Vet pilot results', 'Email nurture: 5-part series for demo requests'] },
          ],
        },
      },
      {
        id: 'market-intel', name: 'Market Intelligence Agent', icon: '📊', status: 'active', budget: 5000, spent: 1200, progress: 95,
        riskScore: 15, reputationScore: 96,
        outputSummary: 'TAM/SAM/SOM analysis with competitive landscape.',
        output: {
          title: 'Market Intelligence Agent Output',
          confidenceScore: 94,
          reasoning: 'Aggregated data from IBISWorld veterinary reports, Crunchbase competitor funding, and 847 clinic survey data points.',
          generatedAt: '2026-06-20T10:52:00Z',
          sections: [
            { heading: 'Market Size', items: ['TAM: $4.2B (US vet clinic software market)', 'SAM: $890M (AI-enabled clinic tools)', 'SOM: $45M (independent clinics, Year 3 target)'] },
            { heading: 'Competitors', items: ['PawPrint AI — $8M raised, scheduling focus, weak revenue tools', 'VetCloud — legacy EHR, no AI, 2,000 clinics', 'PetDesk — communication tool, $12M ARR, potential partner/acquirer'] },
            { heading: 'Pricing Analysis', items: ['Market range: $149-$499/clinic/month', 'Recommended: $299/mo (mid-market, value-aligned)', 'Enterprise (5+ clinics): $249/clinic volume discount'] },
            { heading: 'Market Gaps', items: ['No AI tool combines triage + revenue optimization', 'EHR integrations are shallow across competitors', 'Independent clinics underserved vs. corporate chains'] },
            { heading: 'Opportunities', items: ['Vetspire partnership → 4,000 clinic distribution', 'Corporate vet groups (Banfield, VCA) as Year 2 expansion', 'International: UK/AU vet markets similar structure'] },
            { heading: 'Recommendations', items: ['Lead with revenue recovery messaging', 'Target 2-3 vet clinics in Southeast US first', 'Build Vetspire integration as competitive moat'] },
          ],
        },
      },
      {
        id: 'risk', name: 'Risk Agent', icon: '🛡️', status: 'active', budget: 8000, spent: 3200, progress: 75,
        riskScore: 55, reputationScore: 88,
        outputSummary: 'Risk register with mitigation strategies.',
        output: {
          title: 'Risk Agent — Risk Assessment',
          confidenceScore: 87,
          reasoning: 'Systematic evaluation across technical, market, regulatory, financial, and operational dimensions.',
          generatedAt: '2026-06-20T10:54:00Z',
          sections: [
            { heading: 'Critical Risks', items: ['HIPAA non-compliance → fines up to $1.5M (Mitigation: legal review in progress)', 'AI misdiagnosis liability (Mitigation: vet-in-loop requirement, disclaimers)', 'Single EHR dependency on Vetspire (Mitigation: ezyVet as backup)'] },
            { heading: 'Moderate Risks', items: ['Competitor PawPrint AI GTM acceleration', 'Longer sales cycle than projected (45 vs 30 days)', 'Key person dependency on founding engineer'] },
          ],
        },
      },
      {
        id: 'governance', name: 'Governance Agent', icon: '⚖️', status: 'active', budget: 10000, spent: 4500, progress: 80,
        riskScore: 20, reputationScore: 90,
        outputSummary: 'Corporate governance framework established.',
        output: {
          title: 'Governance Agent — Framework',
          confidenceScore: 90,
          reasoning: 'Applied Delaware C-Corp best practices for pre-seed startups with board governance requirements.',
          generatedAt: '2026-06-20T10:56:00Z',
          sections: [
            { heading: 'Governance Structure', items: ['Delaware C-Corp (incorporated)', '3-person AI Board of Directors', 'Quarterly board reviews + monthly treasury reports'] },
            { heading: 'Policies', items: ['Spend approval matrix (see Treasury)', 'Data retention: 7 years HIPAA compliance', 'Conflict of interest disclosure for advisors'] },
            { heading: 'Compliance Checklist', items: ['✅ Certificate of incorporation', '✅ 83(b) election filed', '⏳ HIPAA BAA templates (legal review)', '⏳ SOC 2 Type I (planned Q3)'] },
          ],
        },
      },
    ],
    investors: [
      { id: 'inv1', name: 'Sarah Chen', firm: 'Bessemer Venture Partners', matchScore: 92, thesis: 'Vertical AI SaaS in underserved industries', stageFit: 'Seed', industryFit: 'Healthcare AI', warmIntroProbability: 78, recommendedOutreach: 'Warm intro via Dr. James Park (Bessemer portfolio, VetTech)', portfolio: ['Toast', 'Shopify', 'PagerDuty'], checkSize: '$2-5M', focus: ['Vertical SaaS', 'AI/ML', 'Healthcare'] },
      { id: 'inv2', name: 'Marcus Webb', firm: 'a16z Bio+Health', matchScore: 88, thesis: 'AI-native healthcare workflows', stageFit: 'Pre-Seed/Seed', industryFit: 'Vet + Healthcare', warmIntroProbability: 45, recommendedOutreach: 'Apply via a16z START program + LinkedIn thought leadership', portfolio: ['Freenome', 'Devoted Health'], checkSize: '$1-3M', focus: ['Bio+Health', 'AI Diagnostics'] },
      { id: 'inv3', name: 'Priya Sharma', firm: 'First Round Capital', matchScore: 85, thesis: 'Founder-first seed investments in B2B SaaS', stageFit: 'Seed', industryFit: 'B2B SaaS', warmIntroProbability: 62, recommendedOutreach: 'Introduction via First Round Angel Track alumni network', portfolio: ['Notion', 'Roblox', 'Square'], checkSize: '$500K-3M', focus: ['B2B SaaS', 'Marketplace'] },
      { id: 'inv4', name: 'David Okonkwo', firm: 'Tiger Global', matchScore: 71, thesis: 'Growth-stage vertical software', stageFit: 'Series A+', industryFit: 'Vertical SaaS', warmIntroProbability: 25, recommendedOutreach: 'Re-engage post $1M ARR milestone', portfolio: ['Toast', 'Spotify'], checkSize: '$5-20M', focus: ['Vertical SaaS', 'Global expansion'] },
      { id: 'inv5', name: 'Emily Foster', firm: 'Lux Capital', matchScore: 79, thesis: 'Deep tech and science-driven startups', stageFit: 'Seed', industryFit: 'Health + AI', warmIntroProbability: 55, recommendedOutreach: 'Submit through Lux scientific advisory board referral', portfolio: ['Eikon Therapeutics', 'Variant Bio'], checkSize: '$1-5M', focus: ['Deep Tech', 'Life Sciences'] },
    ],
    customers: [
      { id: 'c1', name: 'Blue Ridge Veterinary Group', type: 'design_partner', leadScore: 94, expectedRevenue: 3588, industry: 'Multi-location vet practice', painPoints: ['Missed billing on add-on services', 'High no-show rate (18%)'], status: 'LOI Signed' },
      { id: 'c2', name: 'Paws & Claws Animal Hospital', type: 'pilot', leadScore: 87, expectedRevenue: 3588, industry: 'Single clinic, 3 vets', painPoints: ['Manual scheduling inefficiency', 'No triage before appointments'], status: 'Demo Scheduled' },
      { id: 'c3', name: 'Sunset Pet Wellness', type: 'potential', leadScore: 76, expectedRevenue: 3588, industry: 'Holistic vet clinic', painPoints: ['Limited tech stack', 'Owner resistance to AI'], status: 'Outreach Sent' },
      { id: 'c4', name: 'MetroVet Emergency Clinic', type: 'potential', leadScore: 82, expectedRevenue: 5988, industry: 'Emergency vet (premium tier)', painPoints: ['Triage bottleneck during peak hours', 'Staff burnout from phone triage'], status: 'Qualified Lead' },
      { id: 'c5', name: 'Greenfield Animal Care', type: 'design_partner', leadScore: 91, expectedRevenue: 3588, industry: 'Rural vet clinic', painPoints: ['Revenue leakage from incomplete records', 'No analytics on service mix'], status: 'Pilot Active' },
    ],
    ecosystem: {
      nodes: [
        { id: 'company', label: 'VetPulse AI', type: 'company', description: 'Your autonomous company' },
        { id: 'inv-bessemer', label: 'Bessemer VP', type: 'investor', description: 'Top match — 92% fit' },
        { id: 'inv-a16z', label: 'a16z Bio+Health', type: 'investor', description: 'Healthcare AI focus' },
        { id: 'adv-james', label: 'Dr. James Park', type: 'advisor', description: 'Vet industry advisor, Bessemer connection' },
        { id: 'law-morrison', label: 'Morrison & Foerster', type: 'lawyer', description: 'Startup legal, HIPAA expertise' },
        { id: 'patent-ip', label: 'IP Strategy Co.', type: 'patent', description: 'AI triage algorithm patent filing' },
        { id: 'ca-finops', label: 'FinOps Partners', type: 'ca', description: 'Bookkeeping + tax for startups' },
        { id: 'audit-deloitte', label: 'Deloitte Startup', type: 'auditor', description: 'SOC 2 audit partner' },
        { id: 'partner-vetspire', label: 'Vetspire', type: 'partner', description: 'EHR integration partner — 4K clinics' },
        { id: 'expert-vet', label: 'Dr. Lisa Nguyen', type: 'expert', description: '20yr vet, product validation' },
      ],
      edges: [
        { source: 'company', target: 'inv-bessemer' },
        { source: 'company', target: 'inv-a16z' },
        { source: 'company', target: 'adv-james' },
        { source: 'adv-james', target: 'inv-bessemer' },
        { source: 'company', target: 'law-morrison' },
        { source: 'company', target: 'patent-ip' },
        { source: 'company', target: 'ca-finops' },
        { source: 'company', target: 'audit-deloitte' },
        { source: 'company', target: 'partner-vetspire' },
        { source: 'company', target: 'expert-vet' },
        { source: 'partner-vetspire', target: 'expert-vet' },
      ],
    },
    board: [
      { id: 'b1', name: 'Finance Director AI', role: 'Finance Director', opinion: 'Approve seed raise preparation but delay hiring until $500K committed', reasoning: 'Current burn rate of $18.5K/mo is sustainable for 13 months, but adding 2 engineers pre-seed would reduce runway to 8 months. Recommend securing lead investor before expanding team.', vote: 'conditional', recommendation: 'Proceed with seed fundraise; freeze hiring until term sheet signed', decision: 'Conditional approval on hiring freeze', confidence: 88 },
      { id: 'b2', name: 'Risk Director AI', role: 'Risk Director', opinion: 'HIPAA compliance must be completed before any pilot with real patient data', reasoning: 'Three pilot clinics are ready but none have signed BAAs. Operating without HIPAA compliance exposes company to $100K-$1.5M fine risk per incident.', vote: 'approve', recommendation: 'Accelerate legal review; use synthetic data for demos until compliance complete', decision: 'Approved with compliance gate', confidence: 94 },
      { id: 'b3', name: 'Growth Director AI', role: 'Growth Director', opinion: 'Strongly approve VMX conference booth investment', reasoning: 'VMX attendance includes 17,000 veterinary professionals. Competitor PawPrint AI confirmed booth presence. Missing this event cedes market awareness. ROI projection: 15-20 qualified leads at $400 CAC.', vote: 'approve', recommendation: 'Approve $8,000 VMX booth + $500 demo materials budget', decision: 'Approved', confidence: 91 },
    ],
    wallets: [
      { id: 'founder', name: 'Founder Wallet', balance: 45200, budget: 50000, spent: 4800, color: '#6366f1' },
      { id: 'marketing', name: 'Marketing Wallet', balance: 18800, budget: 25000, spent: 6200, color: '#ec4899' },
      { id: 'engineering', name: 'Engineering Wallet', balance: 58000, budget: 80000, spent: 22000, color: '#06b6d4' },
      { id: 'hr', name: 'HR Wallet', balance: 18000, budget: 20000, spent: 2000, color: '#8b5cf6' },
      { id: 'operations', name: 'Operations Wallet', balance: 28500, budget: 35000, spent: 6500, color: '#f59e0b' },
    ],
    spendRequests: [
      { id: 'sr1', title: 'VMX 2026 Conference Booth', department: 'Marketing', amount: 8000, status: 'pending', description: 'Premier veterinary conference — 17K attendees, competitor presence confirmed' },
      { id: 'sr2', title: 'Google Cloud Credits Extension', department: 'Engineering', amount: 2400, status: 'pending', description: 'Additional GCP credits for AI model training and staging environment' },
      { id: 'sr3', title: 'LinkedIn Ad Campaign — Vet Clinic Owners', department: 'Marketing', amount: 500, status: 'pending', description: '2-week targeted campaign to clinic owners in Southeast US' },
      { id: 'sr4', title: 'HIPAA Legal Review', department: 'Operations', amount: 3500, status: 'approved', description: 'Morrison & Foerster — BAA templates and compliance audit' },
      { id: 'sr5', title: 'Part-time Vet Domain Advisor', department: 'HR', amount: 3000, status: 'approved', description: 'Dr. Lisa Nguyen — 3 months product validation advisory' },
    ],
    monadActivities: [
      { id: 'm1', type: 'Decision Recorded', hash: '0x7f3a...b2c9', timestamp: '2026-06-20 09:15 UTC', description: 'Board approved HIPAA compliance gate for pilot program' },
      { id: 'm2', type: 'Approval Recorded', hash: '0x4e8d...a1f3', timestamp: '2026-06-20 09:42 UTC', description: 'Treasury allocation: Engineering 40%, GTM 25%' },
      { id: 'm3', type: 'Reputation Updated', hash: '0x9c2b...d4e7', timestamp: '2026-06-20 10:08 UTC', description: 'Market Intelligence Agent reputation +2 (accurate TAM analysis)' },
      { id: 'm4', type: 'Treasury Allocation Completed', hash: '0x1a5f...c8b2', timestamp: '2026-06-20 10:22 UTC', description: 'Marketing wallet funded: $25,000' },
      { id: 'm5', type: 'Decision Recorded', hash: '0x6d9e...f1a4', timestamp: '2026-06-20 10:45 UTC', description: 'Pricing decision: $299/clinic/month recorded on-chain' },
      { id: 'm6', type: 'Company Memory Stored', hash: '0x3b7c...e5d8', timestamp: '2026-06-20 11:02 UTC', description: 'Blue Ridge Vet LOI signed — stored in company memory ledger' },
    ],
    memory: [
      { id: 'mem1', category: 'Decision', title: 'Pricing set at $299/clinic/month', date: '2026-06-18', outcome: 'Validated against 847-clinic survey data', roi: 'Projected 82% gross margin', lesson: 'Mid-market pricing maximizes conversion without undervaluing' },
      { id: 'mem2', category: 'Campaign', title: 'LinkedIn outreach to 50 clinic owners', date: '2026-06-10', outcome: '12 responses, 5 demos booked', roi: '24% response rate, $0 spend', lesson: 'Personalized messages referencing clinic name 3x better than generic' },
      { id: 'mem3', category: 'Outreach', title: 'Warm intro request to Bessemer via Dr. Park', date: '2026-06-15', outcome: 'Intro pending — expected within 2 weeks', lesson: 'Portfolio founder intros convert 4x vs cold outreach' },
      { id: 'mem4', category: 'Treasury', title: 'Engineering wallet initial allocation', date: '2026-06-01', outcome: '$80K allocated, 27.5% spent in 3 weeks', roi: 'On-track for MVP in 6 weeks', lesson: 'Front-load engineering spend for MVP critical path' },
      { id: 'mem5', category: 'Decision', title: 'Vetspire chosen as primary EHR integration', date: '2026-05-28', outcome: 'API access requested, sandbox pending', lesson: 'Distribution partnership > feature parity when choosing integrations' },
    ],
    approvals: [
      { id: 'ap1', type: 'campaign', title: 'VMX 2026 Conference Booth', description: 'Premier veterinary conference booth rental + materials', amount: 8000, requestedBy: 'Marketing Agent', status: 'pending' },
      { id: 'ap2', type: 'treasury', title: 'Engineering Cloud Credits', description: 'GCP credits for AI model training infrastructure', amount: 2400, requestedBy: 'CTO Agent', status: 'pending' },
      { id: 'ap3', type: 'investor', title: 'Bessemer Warm Intro Campaign', description: 'Prepare customized deck + schedule intro meeting with Sarah Chen', requestedBy: 'Investor Intelligence Agent', status: 'pending' },
      { id: 'ap4', type: 'partnership', title: 'Vetspire Marketplace Listing', description: 'Apply for Vetspire app marketplace — 4,000 clinic distribution', requestedBy: 'Growth Agent', status: 'pending' },
      { id: 'ap5', type: 'hiring', title: 'Vet Domain Advisor — Dr. Lisa Nguyen', description: '3-month part-time advisory at $3,000/month', amount: 9000, requestedBy: 'HR Agent', status: 'approved' },
    ],
  }
}

export const RECOMMENDED_ACTIONS = [
  'Sign HIPAA BAA templates before activating pilot clinics with real data',
  'Approve VMX conference booth ($8K) — competitor confirmed attendance',
  'Send warm intro request to Bessemer via Dr. James Park this week',
  'Complete Vetspire sandbox integration — 3 pilot clinics blocked',
  'Launch LinkedIn campaign ($500) targeting Southeast clinic owners',
  'Convert "Revenue Recovery" messaging across all marketing materials',
  'Schedule board review of Q2 OKRs and treasury reallocation',
  'Record pricing decision on Monad governance ledger',
  'Onboard Greenfield Animal Care as second active design partner',
  'Prepare seed deck v3 with updated financial model and TAM analysis',
]
