"""Add orchestration models

Revision ID: 96795e0a7a88
Revises: 393017ef1d05
Create Date: 2026-05-16 09:41:40.943536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96795e0a7a88'
down_revision: Union[str, None] = '393017ef1d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orchestration_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_name', sa.String(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orchestration_sessions_id'), 'orchestration_sessions', ['id'], unique=False)
    op.create_table('orchestration_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('log_level', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['orchestration_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orchestration_logs_id'), 'orchestration_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orchestration_logs_id'), table_name='orchestration_logs')
    op.drop_table('orchestration_logs')
    op.drop_index(op.f('ix_orchestration_sessions_id'), table_name='orchestration_sessions')
    op.drop_table('orchestration_sessions')
    # ### end Alembic commands ###
