'use client'

import { useState, useEffect, useCallback, useMemo } from 'react'
import { useRouter } from 'next/navigation'
import { cn } from '@/lib/utils'
import toast from 'react-hot-toast'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { CardWatermark } from '@/components/ui/card-watermark'
import { Icons } from '@/components/ui/icons'
import { InsightCard, type Insight } from '@/components/ai/insights/InsightCard'
import { PatternCluster, type Pattern } from '@/components/ai/insights/PatternCluster'
import { ActionCard, type ActionItem } from '@/components/ai/insights/ActionCard'
import { apiClient } from '@/lib/api-client'

// Tab configuration
interface Tab {
  id: string
  label: string
  icon: React.ElementType
}

const tabs: Tab[] = [
  { id: 'summary', label: 'Summary', icon: Icons.activity },
  { id: 'patterns', label: 'Patterns', icon: Icons.layers },
  { id: 'actions', label: 'Actions', icon: Icons.zap },
]

export default function AIInsightsPage() {
  const [activeTab, setActiveTab] = useState('summary')
  const [insights, setInsights] = useState<Insight[]>([])
  const [patterns, setPatterns] = useState<Pattern[]>([])
  const [actions, setActions] = useState<ActionItem[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [isAnalyzing, setIsAnalyzing] = useState(false)
  const router = useRouter()

  const fetchInsights = useCallback(async () => {
    setIsLoading(true)
    try {
      const data = await apiClient.get<any[]>('/api/insights')
      if (data && data.length > 0) {
        // Map backend fields to frontend Insight interface
        const mapped: Insight[] = data.map((d: any) => ({
          id: d.id,
          type: d.type || 'recommendation',
          severity: d.severity || 'info',
          title: d.title || 'Untitled Insight',
          description: d.description || '',
          data: d.data || {},
          suggested_action: d.suggested_action || undefined,
          action_type: d.action_type || undefined,
          confidence: d.confidence || undefined,
          created_at: d.created_at || new Date().toISOString(),
          is_demo: d.is_demo === 'true',
        }))
        setInsights(mapped)
      } else {
        setInsights([])
      }
      setPatterns([])
      setActions([])
    } catch (e) {
      console.error('Failed to fetch insights:', e)
      setInsights([])
      setPatterns([])
      setActions([])
    } finally {
      setIsLoading(false)
    }
  }, [])

  useEffect(() => {
    fetchInsights()
  }, [fetchInsights])

  const handleAnalyze = async () => {
    setIsAnalyzing(true)
    try {
      // Request AI analysis from the backend (powered by Gemini)
      await apiClient.post('/api/insights/analyze')
      
      toast.success('New insight generated by AI')
      
      // Refresh the list
      await fetchInsights()
    } catch (e: any) {
      console.error('Analysis failed:', e)
      toast.error(e?.message || 'Failed to generate insight. Check your Gemini API key.')
    } finally {
      setIsAnalyzing(false)
    }
  }

  const handleInsightAction = useCallback(async (insight: Insight) => {
    // Route based on action_type
    switch (insight.action_type) {
      case 'create_policy':
        router.push('/ai/policies?tab=create-with-ai')
        break
      case 'investigate':
      case 'review_duplicate':
        router.push('/workbench')
        break
      default:
        break
    }
  }, [router])

  const handleDismissInsight = useCallback(async (id: string) => {
    // Optimistic UI update
    setInsights(prev => prev.filter(i => i.id !== id))
    
    try {
      await apiClient.delete(`/api/insights/${id}`)
    } catch (e) {
      console.error('Failed to dismiss insight:', e)
      // Revert if failed
      fetchInsights()
    }
  }, [fetchInsights])

  const handleApplyAction = useCallback(async (action: ActionItem) => {
    // Route based on action type
    switch (action.action_type) {
      case 'create_policy':
        router.push('/ai/policies?tab=create-with-ai')
        break
      case 'investigate':
      case 'review_transaction':
        router.push('/workbench')
        break
      default:
        break
    }
  }, [router])

  // Stats for summary — Memoized
  const { criticalCount, warningCount, infoCount } = useMemo(() => ({
    criticalCount: insights.filter(i => i.severity === 'critical').length,
    warningCount: insights.filter(i => i.severity === 'warning').length,
    infoCount: insights.filter(i => i.severity === 'info').length,
  }), [insights])

  return (
    <div className="space-y-6 animate-in fade-in duration-200">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-display-3 font-bold tracking-tight text-brand-navy lg:text-display-2">
            AI Insights
          </h1>
          <p className="mt-2 text-lg text-muted-foreground">
            AI-powered analysis of your data. Discover patterns, anomalies, and optimization opportunities.
          </p>
        </div>
        <Button
          variant="gradient"
          onClick={handleAnalyze}
          disabled={isAnalyzing}
        >
          {isAnalyzing ? (
            <>
              <Icons.loader className="mr-2 h-4 w-4 animate-spin" />
              Analyzing...
            </>
          ) : (
            <>
              <Icons.sparkles className="mr-2 h-4 w-4" strokeWidth={1.5} />
              Run Analysis
            </>
          )}
        </Button>
      </div>

      {/* Info Notice */}
      <div className="rounded-lg border border-blue-200 bg-blue-50 p-4">
        <div className="flex items-start gap-3">
          <Icons.info className="h-5 w-5 text-blue-600 mt-0.5" />
          <div className="flex-1">
            <p className="font-medium text-blue-900">AI-Powered Analysis</p>
            <p className="text-sm text-blue-700 mt-1">
              Click &quot;Run Analysis&quot; to have Gemini AI analyze your real platform data —
              campaigns, budgets, agent activity, and governance policies — and generate actionable insights.
            </p>
          </div>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid gap-4 sm:grid-cols-3">
        <Card className="relative overflow-hidden">
          <CardWatermark opacity={2} scale={0.8} />
          <CardContent className="relative z-10 flex items-center gap-4 py-6">
            <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-red-100">
              <Icons.alertCircle className="h-6 w-6 text-red-600" strokeWidth={1.5} />
            </div>
            <div>
              <p className="text-2xl font-bold text-brand-navy">{criticalCount}</p>
              <p className="text-sm text-muted-foreground">Critical Issues</p>
            </div>
          </CardContent>
        </Card>

        <Card className="relative overflow-hidden">
          <CardWatermark opacity={2} scale={0.8} />
          <CardContent className="relative z-10 flex items-center gap-4 py-6">
            <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-amber-100">
              <Icons.alertTriangle className="h-6 w-6 text-amber-600" strokeWidth={1.5} />
            </div>
            <div>
              <p className="text-2xl font-bold text-brand-navy">{warningCount}</p>
              <p className="text-sm text-muted-foreground">Warnings</p>
            </div>
          </CardContent>
        </Card>

        <Card className="relative overflow-hidden">
          <CardWatermark opacity={2} scale={0.8} />
          <CardContent className="relative z-10 flex items-center gap-4 py-6">
            <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-blue-100">
              <Icons.lightbulb className="h-6 w-6 text-blue-600" strokeWidth={1.5} />
            </div>
            <div>
              <p className="text-2xl font-bold text-brand-navy">{infoCount + patterns.length}</p>
              <p className="text-sm text-muted-foreground">Recommendations</p>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Tab Navigation — CSS-only, no framer-motion layoutId */}
      <div>
        <div className={cn(
          'inline-flex items-center gap-1 rounded-xl p-1',
          'bg-white/50 border border-border/50',
          'backdrop-blur-sm'
        )}>
          {tabs.map((tab) => {
            const isActive = activeTab === tab.id
            const Icon = tab.icon
            
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={cn(
                  'relative flex items-center gap-2 rounded-lg px-4 py-2.5',
                  'text-sm font-medium transition-all duration-150',
                  'focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-cornflower/50',
                  isActive
                    ? 'text-white bg-brand-navy shadow-soft'
                    : 'text-muted-foreground hover:text-foreground hover:bg-white/50'
                )}
              >
                <span className="relative z-10 flex items-center gap-2">
                  <Icon className="h-4 w-4" strokeWidth={1.5} />
                  <span className="hidden sm:inline">{tab.label}</span>
                </span>
              </button>
            )
          })}
        </div>
      </div>

      {/* Tab Content — Simple conditional render, no AnimatePresence */}
      <div className="animate-in fade-in duration-150" key={activeTab}>
        {isLoading ? (
          <div className="flex items-center justify-center py-12">
            <Icons.loader className="h-8 w-8 animate-spin text-brand-cornflower" />
          </div>
        ) : (
          <>
            {activeTab === 'summary' && (
              <Card className="relative overflow-hidden">
                <CardWatermark opacity={2} scale={1} />
                <CardHeader className="relative z-10">
                  <CardTitle>All Insights</CardTitle>
                  <CardDescription>
                    {insights.length} insights generated from your data analysis.
                  </CardDescription>
                </CardHeader>
                <CardContent className="relative z-10 space-y-4">
                  {insights.length === 0 ? (
                    <div className="flex flex-col items-center justify-center py-12 text-center">
                      <div className={cn(
                        'mb-4 flex h-16 w-16 items-center justify-center rounded-2xl',
                        'bg-gradient-to-br from-brand-cornflower/20 to-brand-purple/20'
                      )}>
                        <Icons.lightbulb className="h-8 w-8 text-brand-cornflower" strokeWidth={1.5} />
                      </div>
                      <h3 className="font-display text-lg font-semibold text-brand-navy">
                        No insights yet
                      </h3>
                      <p className="mt-1 max-w-sm text-sm text-muted-foreground">
                        Run an analysis to discover patterns, anomalies, and recommendations.
                      </p>
                      <Button
                        variant="gradient"
                        className="mt-6"
                        onClick={handleAnalyze}
                        disabled={isAnalyzing}
                      >
                        <Icons.sparkles className="mr-2 h-4 w-4" strokeWidth={1.5} />
                        Generate Insights
                      </Button>
                    </div>
                  ) : (
                    insights.map((insight) => (
                      <InsightCard
                        key={insight.id}
                        insight={insight}
                        onAction={handleInsightAction}
                        onDismiss={handleDismissInsight}
                      />
                    ))
                  )}
                </CardContent>
              </Card>
            )}

            {activeTab === 'patterns' && (
              <Card className="relative overflow-hidden">
                <CardWatermark opacity={2} scale={1} />
                <CardHeader className="relative z-10">
                  <CardTitle>Detected Patterns</CardTitle>
                  <CardDescription>
                    Recurring behaviors and trends identified in your data.
                  </CardDescription>
                </CardHeader>
                <CardContent className="relative z-10">
                  <PatternCluster patterns={patterns} />
                </CardContent>
              </Card>
            )}

            {activeTab === 'actions' && (
              <Card className="relative overflow-hidden">
                <CardWatermark opacity={2} scale={1} />
                <CardHeader className="relative z-10">
                  <CardTitle>Recommended Actions</CardTitle>
                  <CardDescription>
                    AI-suggested improvements based on your insights.
                  </CardDescription>
                </CardHeader>
                <CardContent className="relative z-10 space-y-3">
                  {actions.length === 0 ? (
                    <div className="flex flex-col items-center justify-center py-12 text-center">
                      <div className={cn(
                        'mb-4 flex h-12 w-12 items-center justify-center rounded-xl',
                        'bg-muted/50'
                      )}>
                        <Icons.zap className="h-6 w-6 text-muted-foreground" strokeWidth={1.5} />
                      </div>
                      <p className="text-sm text-muted-foreground">
                        No actions recommended at this time.
                      </p>
                    </div>
                  ) : (
                    actions.map((action, idx) => (
                      <ActionCard
                        key={idx}
                        action={action}
                        onApply={handleApplyAction}
                      />
                    ))
                  )}
                </CardContent>
              </Card>
            )}
          </>
        )}
      </div>
    </div>
  )
}
